<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="DESKTOP-FQ8REV2" failures="1" tests="1" name="Tests.CreateTicketPositive" time="45.177" errors="0" timestamp="2025-03-18T11:37:30 IST" skipped="0">
  <testcase classname="Tests.CreateTicketPositive" name="CreateTicketPositiveScenario" time="45.177">
    <failure message="❌ Test Failed: Expected validation message but did not appear." type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: ❌ Test Failed: Expected validation message but did not appear.
at org.testng.Assert.fail(Assert.java:111)
at pages.CreateTicket.clickSubmitButton(CreateTicket.java:291)
at Tests.CreateTicketPositive.CreateTicketPositiveScenario(CreateTicketPositive.java:166)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:686)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:230)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:63)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:992)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:203)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1597)
at org.testng.TestRunner.privateRun(TestRunner.java:739)
at org.testng.TestRunner.run(TestRunner.java:614)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:421)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:413)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:373)
at org.testng.SuiteRunner.run(SuiteRunner.java:312)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1274)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1208)
at org.testng.TestNG.runSuites(TestNG.java:1112)
at org.testng.TestNG.run(TestNG.java:1079)
at com.intellij.rt.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:65)
at com.intellij.rt.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:105)
]]>
    </failure>
    <system-out>
      <![CDATA[Clicked the 'Allow' button.
Clicked the 'Skip' button.
Mobile number '7658967891' has been entered into the 'Mobile Number' field.
Name 'venky' has been entered into the 'Enter your name' field.
<b><font color='blue'>Entered Random Email:</font> <font color='green'>c91uvod4wg@email.com</font></b>
Clicked on the 'Select issue type' ImageView.
Clicked on the 'Login issue' ImageView.
Clicked on the 'Confirm' TextView.
Entered the issue description into the 'Write your issue here...' field.
Successfully clicked the 'Upload Image' button.
Successfully clicked the 'Choose from gallery' button.
Successfully clicked the ImageView with resource-id 'icon_thumbnail'.
✅ Successfully clicked the 'Submit' button.
❌ No validation error message displayed. Test failed!]]>
    </system-out>
  </testcase> <!-- CreateTicketPositiveScenario -->
  <system-out>
    <![CDATA[Clicked the 'Allow' button.
Clicked the 'Skip' button.
Mobile number '7658967891' has been entered into the 'Mobile Number' field.
Name 'venky' has been entered into the 'Enter your name' field.
<b><font color='blue'>Entered Random Email:</font> <font color='green'>c91uvod4wg@email.com</font></b>
Clicked on the 'Select issue type' ImageView.
Clicked on the 'Login issue' ImageView.
Clicked on the 'Confirm' TextView.
Entered the issue description into the 'Write your issue here...' field.
Successfully clicked the 'Upload Image' button.
Successfully clicked the 'Choose from gallery' button.
Successfully clicked the ImageView with resource-id 'icon_thumbnail'.
✅ Successfully clicked the 'Submit' button.
❌ No validation error message displayed. Test failed!]]>
  </system-out>
</testsuite> <!-- Tests.CreateTicketPositive -->
